apiVersion: v1
kind: Service
metadata:
  name: {{ include "marketmind-ai.componentName" (dict "root" . "component" "ai-service") }}
  labels:
    {{- include "marketmind-ai.labels" . | nindent 4 }}
    {{- include "marketmind-ai.selectorLabels" (dict "root" . "component" "ai-service") | nindent 4 }}
spec:
  type: {{ .Values.aiService.service.type }}
  ports:
    - name: http
      port: {{ .Values.aiService.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "marketmind-ai.selectorLabels" (dict "root" . "component" "ai-service") | nindent 4 }}
