apiVersion: v1
kind: Service
metadata:
  name: {{ include "marketmind-ai.componentName" (dict "root" . "component" "qdrant") }}
  labels:
    {{- include "marketmind-ai.labels" . | nindent 4 }}
    {{- include "marketmind-ai.selectorLabels" (dict "root" . "component" "qdrant") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.qdrant.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.qdrant.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "marketmind-ai.selectorLabels" (dict "root" . "component" "qdrant") | nindent 4 }}
