package com.marketmind.common.exception;

public enum ErrorCode {
    BAD_REQUEST,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INVALID_DOCUMENT_URL,
    DOWNLOAD_FAILED,
    DOWNLOAD_TIMEOUT,
    FILE_TOO_LARGE,
    DUPLICATE_DOCUMENT,
    STORAGE_FAILURE,
    INTERNAL_ERROR
}
