package com.marketmind.common.exception;

public enum ErrorCode {
    INVALID_REQUEST,
    VALIDATION_FAILED,
    DUPLICATE_RESOURCE,
    EXTERNAL_SERVICE_FAILURE,
    QDRANT_FAILURE,
    OLLAMA_FAILURE,
    DOCUMENT_DOWNLOAD_FAILED,
    DOCUMENT_EXTRACTION_FAILED,
    EMBEDDING_FAILED,

    // Legacy/internal codes retained while callers migrate to the stable
    // public domain codes above.
    BAD_REQUEST,
    INVALID_PARAMETER,
    MALFORMED_JSON,
    INVALID_ENUM_VALUE,
    VALIDATION_ERROR,
    MISSING_REQUEST_PART,
    FILE_UPLOAD_ERROR,
    UPLOAD_SIZE_EXCEEDED,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INVALID_DOCUMENT_URL,
    DOWNLOAD_FAILED,
    DOWNLOAD_TIMEOUT,
    FILE_TOO_LARGE,
    DUPLICATE_DOCUMENT,
    STORAGE_FAILURE,
    UNSUPPORTED_DOCUMENT_FORMAT,
    DOCUMENT_PARSING_FAILED,
    EXTERNAL_API_FAILURE,
    OLLAMA_UNAVAILABLE,
    QDRANT_UNAVAILABLE,
    INTERNAL_ERROR
}
